### ISSUE TITLE
v1.5.10 beta -- looking for feedback 

### ISSUE THREAD

**Issue by averissimo** [yakyak/yakyak#1214]
I'd like to publish the v1.5.10 beta release in a few days.

Opening this issue to see if there are any big problems with it as there are some significant under-the-hood changes *(tray and backend js compiler for both hangupsjs and yakyak)*

Notable changes:

* Adds spellcheck #1201
* Corrects titlebar in MacOSX #1197 

Under-the-hood:

* **Major change on how tray icon** works, should be much more stable for now on #1200
* **Update to Coffeescript** v2.5.1 from v1.9.3 #1212 and #1211
* Reduces the number of files included in the release by using an ASAR file
* Update deb package #1204
* Switches to using Windows 10's built-in 'tar.exe' #1213

Thanks

**Comment by sriharshachilakapati** [comment]
I'm not getting any notifications since updating to macOS 10.15.5. Seems like a separate issue, because I have updated YakYak first in macOS 10.15.4, and then updated the OS. It showed notifications before updating OS, but not now. Should I open a separate issue for this?

**Comment by averissimo** [comment]
Hummm, super strange as none of the bugfixes / features in newer versions should have an impact on the notifications.

Can you open the console (via menu or Ctrl+Alt+I) and check if there are any errors when you should be receiving a notification.

but please open a new ticket and we can continue the discussion there

**Comment by chomper700** [comment]
I just installed the 1.5.10 beta a few minutes ago, so I'm only able to provide some cursory feedback. Windows 10. I've also gone back and made sure that these issues only exist in 1.5.10 and not in 1.5.9.

* The setting "Show YakYak icon for notifications" no longer functions. It displays a tiny SnoreToast icon instead. I tried toggling it off and on a few times, but no dice.
![notif](https://user-images.githubusercontent.com/30938242/88301155-49b4b700-ccd2-11ea-8e30-8585ff1b304c.png)
* Clicking the notification area tray icon to toggle the window state causes a massive amount of flicker. It appears as if the window is appearing and disappearing numerous times (possibly just a few, possibly dozens or hundreds of times), sometimes as a complete window, and other times as just a drop shadow. [Here's an Imgur GIFV link of it.](https://i.imgur.com/5nVncMl.gifv)
* **Critical issue -- 1.5.10 does not seem releasable until this is resolved**. It is very common now to enter a state in which clicking the notification area tray icon *doesn't toggle the window at all* (this applies to both trying to hide and show the window). When in this state, right-click > "show/hide" still works. Left-click does not work. [Here's an Imgur GIFV link of a few attempts to toggle it hidden, followed by a few attempts to toggle it to visible.](https://i.imgur.com/jomucQ2.gifv) (In this gif, I left-lick the tray icon a few times, then right-click show/hide, then left-click a few more times.) I can reproduce this state by having "start minimized to tray" enabled, fully exiting YakYak, sending myself a new unread message from an alt account, and then relaunching YakYak. This state can also be entered occasionally outside of startup. From my testing, it seems to occur somewhat arbitrarily, but influenced by which conversation is currently active, with certain conversations causing it to happen sometimes, and other conversations causing it to happen other times.

Let me know if you need any additional feedback on these issues.

----

Positive feedback:

* The new zip file with the immensely reduced unzip time (fewer files) is much appreciated.
* Spellcheck works for me, for en-US, although you might want to add a setting to the main menu if that's possible. It was slightly unintuitive to find how to enable it.

**Comment by averissimo** [comment]
Thanks for the feedback, I'm limited in accessing a Windows 10 laptop, so it'll be hard to validate those bugs and fix them.

However, I've just pushed a new version of the beta that:

- Should fix the snore toast icon _(asar related)_
- Adds debugging on what's being called to toggle the window.

I'd ask if you can run your test again and then:

- Open the 'Inspector Console' (console tab)
- Count how many times does the following messages appear _(or screenshot it censuring any personal information)_

`menuaction from main process togglewindow`

`toggle window!`

The first indicates when the tray receives a click to toggle window, while the second is when the actual window 'toggle' happens.

**Comment by averissimo** [comment]
wow, that should not be happening.

> "Show YakYak icon in notifications" seems to actually still not be working. I just checked why. It seems to be fishing for \resources\app.asar\icons\icon@8.png when it should be fishing for \resources\app.asar.unpacked\icons\icon@8.png?

I still don't fully understand how asar works _(the packaging methods we used to reduce number of files)_, but from what I understand the files are in the correct paths _(inside the .asar file it has a metadata file saying that icons are placed outside of it)_

I'll try and fix these issues.

**Comment by chomper700** [comment]
To clarify, I took a look at the command line of the SnoreToast instance that YakYak launched. One of the commands that it passed was "-p [my_path]\resources\app.asar\icons\icon@8.png". That file does not exist on my file system, only "resources\app.asar.unpacked\icons\icon@8.png" does.

I don't know how asar works either, but what I imagine is that _inside_ of your application, you're able to make a reference to "resources\app.asar\icons\icon@8.png", but that since SnoreToast is a _different_ program, it doesn't know what asar is, so it needs to be passed the path to the real file.

----

Speaking of icons, I just noticed that the new black and white tray icon looks incredibly janky. ![icon](https://user-images.githubusercontent.com/30938242/88340620-260d6300-cd0a-11ea-901f-d0a984e14c46.png)

Here are the icons at normal resolution, and then when I zoomed in on them. YakYak has a provided 16x16 icon, but Windows doesn't seem to be using that. It seems to be loading the 32x32 icon and then performing a terrible resize on it. It wasn't obviously ugly until I saw the black and white one.  This is not a new issue though, would you like me to re-file it as its own issue?

**Comment by chomper700** [comment]
I just checked out the tray functionality in the current rolling release of the beta. Most of excessive click events and flashing window seem to be gone, but the tray toggle still fails at the same rate. A successful toggle now only produces one click event, and a failed toggle now only produces two click events.

**Comment by Paradox52525** [comment]
I'm a new user who just installed Yakyak (first 1.5.9, then the latest 1.5.10 beta. I am on Windows 10).  With 1.5.9 I could not get any desktop notifications to work, not even taskbar blinking.  With 1.5.10 the taskbar entry will blink, but I still can't get any kind of popup notifications to work.  I have not changed any of the default settings except for the color scheme, it looks like notifications are enabled.  Any idea what's going on?

**Comment by nmelnick** [comment]
Thanks for the build!

The Windows build still uses a ZIP file extension, which most tools complain about now that it's a tar file. When this starts moving toward release, can the build tool name the file with a .tar extension?

![image](https://user-images.githubusercontent.com/1108298/90398823-0565ce00-e068-11ea-9984-a0dca334dce3.png)
